import { NextRequest, NextResponse } from 'next/server';
import type { TermItem } from '@/lib/types';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// GET /api/print?mode=quiz&theme=space&terms=<base64-json>
// Generates a printable PDF worksheet for the given game mode + terms
export async function GET(req: NextRequest) {
  const url = req.nextUrl;
  const mode = url.searchParams.get('mode') ?? 'quiz';
  const termsB64 = url.searchParams.get('terms');

  if (!termsB64) {
    return NextResponse.json({ error: 'terms required' }, { status: 400 });
  }

  let terms: TermItem[];
  try {
    const cleanB64 = termsB64.replace(/-/g, '+').replace(/_/g, '/');
    const termsJson = Buffer.from(cleanB64, 'base64').toString('utf8');
    terms = JSON.parse(termsJson);
  } catch {
    return NextResponse.json({ error: 'invalid terms encoding' }, { status: 400 });
  }

  if (!Array.isArray(terms) || terms.length === 0) {
    return NextResponse.json({ error: 'no terms' }, { status: 400 });
  }

  // Dynamically import jspdf (pure JS, no external font files needed)
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });

  // Title header
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('MiniStar Lab', doc.internal.pageSize.getWidth() / 2, 50, { align: 'center' });
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(`${mode.charAt(0).toUpperCase() + mode.slice(1)} Worksheet`, doc.internal.pageSize.getWidth() / 2, 72, { align: 'center' });
  doc.setDrawColor(0x7c, 0x3a, 0xed);
  doc.setLineWidth(2);
  doc.line(50, 85, doc.internal.pageSize.getWidth() - 50, 85);

  // Name + Date
  doc.setFontSize(11);
  let y = 110;
  doc.text('Name: ____________________     Date: ___________', 50, y);
  y += 30;

  // Generate content based on mode
  switch (mode) {
    case 'quiz':
      y = generateQuizWorksheet(doc, terms, y);
      break;
    case 'crossword':
      y = generateCrosswordWorksheet(doc, terms, y);
      break;
    case 'wordsearch':
      y = generateWordsearchWorksheet(doc, terms, y);
      break;
    case 'flash-cards':
      y = generateFlashCardsWorksheet(doc, terms, y);
      break;
    case 'match-up':
      y = generateMatchUpWorksheet(doc, terms, y);
      break;
    case 'anagram':
      y = generateAnagramWorksheet(doc, terms, y);
      break;
    default:
      y = generateQuizWorksheet(doc, terms, y);
  }

  // Footer
  y = Math.max(y + 30, doc.internal.pageSize.getHeight() - 40);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(0x94, 0xa3, 0xb8);
  doc.text('Generated by MiniStar English Global Lab', doc.internal.pageSize.getWidth() / 2, doc.internal.pageSize.getHeight() - 25, { align: 'center' });

  const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

  return new NextResponse(pdfBuffer, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `inline; filename="ministar-${mode}-worksheet.pdf"`,
      'Cache-Control': 'no-cache',
    },
  });
}

// ===========================================================================
// QUIZ WORKSHEET
// ===========================================================================
function generateQuizWorksheet(doc: any, terms: TermItem[], y: number): number {
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Quiz Questions', 50, y);
  y += 25;

  terms.forEach((term, i) => {
    if (y > doc.internal.pageSize.getHeight() - 100) { doc.addPage(); y = 60; }
    const question = term.definition ?? `What is "${term.term}"?`;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`${i + 1}. ${question}`, 50, y);
    y += 18;

    const correct = term.term;
    const distractors = terms.filter(t => t.id !== term.id).slice(0, 3).map(t => t.term);
    const options = [...distractors, correct].sort(() => Math.random() - 0.5);
    const letters = ['A', 'B', 'C', 'D'];

    options.forEach((opt, j) => {
      const x = 70 + (j % 2) * 250;
      if (j % 2 === 0 && j > 0) y += 16;
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text(`___ ${letters[j]}) ${opt}`, x, y);
    });
    y += 25;
  });

  // Answer key
  doc.addPage();
  y = 60;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Answer Key', 50, y);
  y += 25;
  terms.forEach((term, i) => {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`${i + 1}. ${term.term}`, 50, y);
    y += 16;
  });
  return y;
}

// ===========================================================================
// CROSSWORD WORKSHEET
// ===========================================================================
function generateCrosswordWorksheet(doc: any, terms: TermItem[], y: number): number {
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Crossword Puzzle', 50, y);
  y += 20;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(0x66, 0x66, 0x66);
  doc.text('(Use the clues to fill in the words)', 50, y);
  doc.setTextColor(0, 0, 0);
  y += 25;

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Across', 50, y);
  y += 18;
  terms.slice(0, Math.ceil(terms.length / 2)).forEach((term, i) => {
    if (y > doc.internal.pageSize.getHeight() - 60) { doc.addPage(); y = 60; }
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`${i + 1}. ${term.definition ?? term.term} (${term.term.length} letters)`, 50, y);
    y += 14;
    doc.text(`     ${term.term.split('').map(() => '___ ').join('')}`, 50, y);
    y += 20;
  });

  y += 10;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Down', 50, y);
  y += 18;
  terms.slice(Math.ceil(terms.length / 2)).forEach((term, i) => {
    if (y > doc.internal.pageSize.getHeight() - 60) { doc.addPage(); y = 60; }
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`${i + 1}. ${term.definition ?? term.term} (${term.term.length} letters)`, 50, y);
    y += 14;
    doc.text(`     ${term.term.split('').map(() => '___ ').join('')}`, 50, y);
    y += 20;
  });

  // Answer key
  doc.addPage();
  y = 60;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Answer Key', 50, y);
  y += 25;
  doc.setFontSize(13);
  doc.text('Across:', 50, y);
  y += 16;
  terms.slice(0, Math.ceil(terms.length / 2)).forEach((term, i) => {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`${i + 1}. ${term.term}`, 50, y);
    y += 14;
  });
  y += 10;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Down:', 50, y);
  y += 16;
  terms.slice(Math.ceil(terms.length / 2)).forEach((term, i) => {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`${i + 1}. ${term.term}`, 50, y);
    y += 14;
  });
  return y;
}

// ===========================================================================
// WORD SEARCH WORKSHEET
// ===========================================================================
function generateWordsearchWorksheet(doc: any, terms: TermItem[], y: number): number {
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Word Search', 50, y);
  y += 20;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(0x66, 0x66, 0x66);
  doc.text('Find these words hidden in the grid (horizontally or vertically):', 50, y);
  doc.setTextColor(0, 0, 0);
  y += 25;

  const gridSize = 12;
  const grid: string[][] = Array.from({ length: gridSize }, () => Array(gridSize).fill(''));
  const words = terms.map(t => t.term.toUpperCase().replace(/[^A-Z]/g, '').slice(0, 10)).filter(w => w.length > 0).slice(0, 8);

  words.forEach((word, i) => {
    const row = i + 1;
    const col = 1;
    for (let c = 0; c < word.length && col + c < gridSize; c++) {
      grid[row][col + c] = word[c];
    }
  });

  for (let r = 0; r < gridSize; r++) {
    for (let c = 0; c < gridSize; c++) {
      if (!grid[r][c]) grid[r][c] = String.fromCharCode(65 + Math.floor(Math.random() * 26));
    }
  }

  const cellSize = 24;
  const gridStartX = 80;
  const gridStartY = y;
  doc.setFont('courier', 'bold');
  doc.setFontSize(14);
  for (let r = 0; r < gridSize; r++) {
    for (let c = 0; c < gridSize; c++) {
      const x = gridStartX + c * cellSize;
      const cy = gridStartY + r * cellSize;
      doc.setDrawColor(0xcc, 0xcc, 0xcc);
      doc.setLineWidth(0.5);
      doc.rect(x, cy, cellSize, cellSize);
      doc.text(grid[r][c], x + cellSize / 2, cy + 16, { align: 'center' });
    }
  }

  y = gridStartY + gridSize * cellSize + 30;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Words to Find:', 50, y);
  y += 18;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  words.forEach((word, i) => {
    doc.text(`${i + 1}. ${word}`, 50, y);
    y += 14;
  });
  return y;
}

// ===========================================================================
// FLASH CARDS WORKSHEET
// ===========================================================================
function generateFlashCardsWorksheet(doc: any, terms: TermItem[], y: number): number {
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Flash Cards', 50, y);
  y += 20;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(0x66, 0x66, 0x66);
  doc.text('Cut along the lines to make individual flash cards.', 50, y);
  doc.setTextColor(0, 0, 0);
  y += 25;

  const cardW = 240;
  const cardH = 90;
  const pageW = doc.internal.pageSize.getWidth() - 100;
  const cols = Math.floor(pageW / cardW);
  const margin = (pageW - cols * cardW) / 2;
  let cardIdx = 0;

  terms.forEach((term) => {
    if (cardIdx >= cols * 3) { doc.addPage(); cardIdx = 0; y = 80; }
    const col = cardIdx % cols;
    const row = Math.floor(cardIdx / cols);
    const x = 50 + margin + col * cardW;
    const cy = 80 + row * (cardH + 10);

    doc.setDrawColor(0x7c, 0x3a, 0xed);
    doc.setLineWidth(1.5);
    doc.rect(x, cy, cardW, cardH);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(term.emoji ?? '?', x + 10, cy + 20);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(term.term, x + 10, cy + 40);

    doc.setDrawColor(0xcc, 0xcc, 0xcc);
    doc.setLineWidth(0.5);
    doc.setLineDashPattern([3, 3], 0);
    doc.line(x, cy + cardH / 2, x + cardW, cy + cardH / 2);
    doc.setLineDashPattern([], 0);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(0x66, 0x66, 0x66);
    const def = doc.splitTextToSize(term.definition ?? '', cardW - 20);
    doc.text(def, x + 10, cy + cardH / 2 + 14);
    doc.setTextColor(0, 0, 0);

    cardIdx++;
  });
  return y;
}

// ===========================================================================
// MATCH UP WORKSHEET
// ===========================================================================
function generateMatchUpWorksheet(doc: any, terms: TermItem[], y: number): number {
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Match Up', 50, y);
  y += 20;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(0x66, 0x66, 0x66);
  doc.text('Draw a line to match each word with its definition.', 50, y);
  doc.setTextColor(0, 0, 0);
  y += 30;

  const shuffledDefs = [...terms].sort(() => Math.random() - 0.5);
  const leftX = 60;
  const rightX = 320;

  doc.setFontSize(11);
  terms.forEach((term, i) => {
    if (y > doc.internal.pageSize.getHeight() - 60) { doc.addPage(); y = 60; }
    doc.setFont('helvetica', 'bold');
    doc.text(`${i + 1}.`, leftX, y);
    doc.setFont('helvetica', 'normal');
    doc.text(term.term, leftX + 25, y);
    const letter = String.fromCharCode(65 + i);
    doc.setFont('helvetica', 'bold');
    doc.text(`${letter}.`, rightX, y);
    doc.setFont('helvetica', 'normal');
    const def = doc.splitTextToSize(shuffledDefs[i].definition ?? shuffledDefs[i].term, 200);
    doc.text(def, rightX + 25, y);
    y += 35;
  });

  y += 15;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Answer Key:', 50, y);
  y += 18;
  terms.forEach((term, i) => {
    const matchLetter = String.fromCharCode(65 + shuffledDefs.findIndex(t => t.id === term.id));
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`${i + 1}. -> ${matchLetter}`, 50, y);
    y += 14;
  });
  return y;
}

// ===========================================================================
// ANAGRAM WORKSHEET
// ===========================================================================
function generateAnagramWorksheet(doc: any, terms: TermItem[], y: number): number {
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Anagram Puzzle', 50, y);
  y += 20;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(0x66, 0x66, 0x66);
  doc.text('Unscramble the letters to spell each word.', 50, y);
  doc.setTextColor(0, 0, 0);
  y += 30;

  terms.forEach((term, i) => {
    if (y > doc.internal.pageSize.getHeight() - 80) { doc.addPage(); y = 60; }
    const word = term.term.toUpperCase();
    const scrambled = word.split('').sort(() => Math.random() - 0.5).join(' ');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`${i + 1}. Scrambled:`, 50, y);
    y += 18;
    doc.setFontSize(16);
    doc.setFont('courier', 'bold');
    doc.setTextColor(0x7c, 0x3a, 0xed);
    doc.text(`    ${scrambled}`, 50, y);
    doc.setTextColor(0, 0, 0);
    y += 16;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(0x66, 0x66, 0x66);
    doc.text(`    Hint: ${term.definition ?? 'A vocabulary word'}`, 50, y);
    doc.setTextColor(0, 0, 0);
    y += 16;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`    Answer: ${'_'.repeat(word.length + 5)}`, 50, y);
    y += 30;
  });

  doc.addPage();
  y = 60;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Answer Key', 50, y);
  y += 25;
  terms.forEach((term, i) => {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`${i + 1}. ${term.term}`, 50, y);
    y += 14;
  });
  return y;
}
